elasticsearch:
  image: elasticsearch:1.7.1

kibana:
  image: kibana:4.1.1
  links:
    - nginx:elasticsearch
  ports:
    - "5601:5601"
  extra_hosts:
    - "sandbox.docido.com:192.168.99.100"

logstash:
  build: logstash
  links:
    - nginx:elasticsearch

nginx:
  build: nginx
  links:
    - elasticsearch:elasticsearch
  ports:
    - "9200:9200"
flask:
  build: flask
  links:
    - kibana:kibana
  ports:
    - "5000:5000"
