elasticsearch:
  image: elasticsearch:1.7.1
authproxy:
  build: es-kibana-auth-proxy
  command: npm start -- -f company
  links:
    - elasticsearch:elasticsearch

kibana:
  build: kibana
  links:
    - authproxy:elasticsearch
  extra_hosts:
    - "sandbox.docido.com:192.168.99.100"

logstash:
  build: logstash
  links:
    - elasticsearch:elasticsearch

flask:
  build: flask
  links:
    - kibana:kibana
  ports:
    - "5000:5000"
